// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DigitalsController from "./digitals_controller"
application.register("digitals", DigitalsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

import YearsController from "./years_controller"
application.register("years", YearsController)
